# Generated by Django 4.2 on 2025-10-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='oeuvres/', verbose_name='Image')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pixelette.oeuvre', verbose_name='Œuvre')),
            ],
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='Pixelette.utilisateur', verbose_name='Auteur'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('commentaire', 'Commentaire')], max_length=20, verbose_name="Type d'interaction")),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu du commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pixelette.oeuvre', verbose_name='Œuvre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pixelette.utilisateur', verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la galerie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('privee', models.BooleanField(default=False, verbose_name='Privée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeries', to='Pixelette.utilisateur', verbose_name='Propriétaire')),
            ],
        ),
    ]
