# Generated by Django 4.2.25 on 2025-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Image de profil'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='123456', max_length=128, verbose_name='Mot de passe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default='ranim', max_length=100, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='two_factor_temp_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
