# Generated by Django 4.2.25 on 2025-10-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Mot de passe'),
        ),
    ]
