# Generated by Django 4.2.25 on 2025-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0002_utilisateur_image_utilisateur_is_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('artiste', 'Artiste'), ('admin', 'Admin')], default='user', max_length=10, verbose_name='Rôle'),
        ),
    ]
