# Generated by Django 4.2.25 on 2025-10-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0003_utilisateur_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
    ]
