# Generated by Django 4.2.25 on 2025-10-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0003_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouveau_role', models.CharField(default='artiste', max_length=10, verbose_name='Nouveau rôle demandé')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10, verbose_name='Statut')),
                ('raison', models.TextField(blank=True, verbose_name='Raison (optionnelle)')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='Pixelette.utilisateur', verbose_name='Utilisateur')),
            ],
        ),
    ]
