# Generated by Django 4.2.25 on 2025-10-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0004_remove_utilisateur_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
