# Generated by Django 4.2.25 on 2025-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0005_utilisateur_prenom_utilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Image de profil'),
        ),
    ]
