# Generated by Django 4.2.25 on 2025-10-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0006_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='reset_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reset_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
