# Generated by Django 4.2 on 2025-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0007_utilisateur_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='oeuvres',
            field=models.ManyToManyField(blank=True, related_name='galeries_associees', to='Pixelette.oeuvre', verbose_name='Oeuvres'),
        ),
        migrations.AddField(
            model_name='galerie',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thème'),
        ),
    ]
