# Generated by Django 4.2 on 2025-10-11 00:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0008_galerie_oeuvres_galerie_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalerieInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Token d'invitation")),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('acceptee', models.BooleanField(default=False, verbose_name='Acceptée')),
                ('date_acceptation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('galerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='Pixelette.galerie', verbose_name='Galerie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_invitations', to='Pixelette.utilisateur', verbose_name='Utilisateur invité')),
            ],
            options={
                'verbose_name': 'Invitation à une galerie',
                'verbose_name_plural': 'Invitations aux galeries',
                'unique_together': {('galerie', 'utilisateur')},
            },
        ),
    ]
