# Generated by Django 4.2.25 on 2025-10-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0009_galerieinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
