# Generated by Django 5.2.7 on 2025-10-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0010_alter_utilisateur_is_two_factor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateTimeField(auto_now_add=True, verbose_name='Date de suivi')),
                ('artiste', models.ForeignKey(limit_choices_to={'role': 'artiste'}, on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='Pixelette.utilisateur', verbose_name='Artiste suivi')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='Pixelette.utilisateur', verbose_name='Utilisateur qui suit')),
            ],
            options={
                'verbose_name': 'Suivi',
                'verbose_name_plural': 'Suivis',
                'ordering': ['-date_suivi'],
                'unique_together': {('utilisateur', 'artiste')},
            },
        ),
    ]
