# Generated by Django 4.2 on 2025-10-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0010_alter_utilisateur_is_two_factor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chart_type', models.CharField(choices=[('pie', 'Pie'), ('bar', 'Bar'), ('line', 'Line')], default='pie', max_length=20)),
                ('subject', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('oeuvre', 'Oeuvre'), ('galerie', 'Galerie')], max_length=30)),
                ('subject_field', models.CharField(help_text='Field on subject model to group/count by', max_length=200)),
                ('config', models.JSONField(blank=True, help_text='Optional JSON config/filters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_stats', to='Pixelette.utilisateur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
