# Generated by Django 4.2.16 on 2025-10-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0010_alter_utilisateur_is_two_factor_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-date'], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AddField(
            model_name='interaction',
            name='plateforme_partage',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('email', 'Email'), ('link', 'Lien direct')], max_length=50, verbose_name='Plateforme de partage'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Pixelette.oeuvre', verbose_name='Œuvre'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('commentaire', 'Commentaire'), ('partage', 'Partage')], max_length=20, verbose_name="Type d'interaction"),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Pixelette.utilisateur', verbose_name='Utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('utilisateur', 'oeuvre', 'type')},
        ),
    ]
