# Generated by Django 5.2.7 on 2025-10-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0011_alter_interaction_options_and_more'),
        ('Pixelette', '0011_suivi'),
    ]

    operations = [
    ]
