# Generated by Django 4.2 on 2025-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0011_savedstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='vues',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='vues',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='savedstat',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'Pie'), ('donut', 'Donut'), ('bar', 'Bar'), ('line', 'Line'), ('area', 'Area'), ('treemap', 'Treemap'), ('radar', 'Radar'), ('radialBar', 'RadialBar')], default='pie', max_length=20),
        ),
    ]
