# Generated by Django 5.2.7 on 2025-10-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0011_suivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='score_artiste',
            field=models.IntegerField(default=0, verbose_name='Score Artiste (0-100)'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='score_artiste_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour du score'),
        ),
    ]
