# Generated by Django 5.2.7 on 2025-10-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0012_utilisateur_score_artiste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to='Pixelette.utilisateur')),
            ],
            options={
                'verbose_name': 'Connexion',
                'verbose_name_plural': 'Connexions',
                'ordering': ['-date_connexion'],
                'indexes': [models.Index(fields=['utilisateur', '-date_connexion'], name='Pixelette_c_utilisa_71d08d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultationOeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oeuvre_id', models.IntegerField()),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Pixelette.utilisateur')),
            ],
            options={
                'verbose_name': "Consultation d'œuvre",
                'verbose_name_plural': "Consultations d'œuvres",
                'ordering': ['-date_consultation'],
                'indexes': [models.Index(fields=['utilisateur', '-date_consultation'], name='Pixelette_c_utilisa_531a5c_idx'), models.Index(fields=['oeuvre_id'], name='Pixelette_c_oeuvre__e895dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactArtiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(default='Demande de contact', max_length=200)),
                ('message', models.TextField()),
                ('date_contact', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False, verbose_name="Message lu par l'artiste")),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_recus', to='Pixelette.utilisateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_envoyes', to='Pixelette.utilisateur')),
            ],
            options={
                'verbose_name': 'Contact artiste',
                'verbose_name_plural': 'Contacts artistes',
                'ordering': ['-date_contact'],
                'indexes': [models.Index(fields=['utilisateur', '-date_contact'], name='Pixelette_c_utilisa_17b9fd_idx'), models.Index(fields=['artiste', 'lu'], name='Pixelette_c_artiste_880d44_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartageOeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oeuvre_id', models.IntegerField()),
                ('plateforme', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('date_partage', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='Pixelette.utilisateur')),
            ],
            options={
                'verbose_name': "Partage d'œuvre",
                'verbose_name_plural': "Partages d'œuvres",
                'ordering': ['-date_partage'],
                'indexes': [models.Index(fields=['utilisateur', '-date_partage'], name='Pixelette_p_utilisa_540b46_idx')],
            },
        ),
    ]
