# Generated by Django 4.2 on 2025-10-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0011_suivi'),
        ('Pixelette', '0012_galerie_vues_oeuvre_vues_alter_savedstat_chart_type'),
    ]

    operations = [
    ]
