# Generated by Django 5.2.7 on 2025-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0012_merge_20251018_1948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'like')), fields=('utilisateur', 'oeuvre'), name='unique_like_per_user_oeuvre'),
        ),
    ]
