# Generated by Django 5.2.7 on 2025-10-21 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0013_connexion_consultationoeuvre_contactartiste_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-date'], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AddField(
            model_name='interaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='Pixelette.interaction', verbose_name='Commentaire parent'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='plateforme_partage',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('email', 'Email'), ('link', 'Lien direct')], max_length=50, verbose_name='Plateforme de partage'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Pixelette.oeuvre', verbose_name='Œuvre'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('commentaire', 'Commentaire'), ('partage', 'Partage')], max_length=20, verbose_name="Type d'interaction"),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Pixelette.utilisateur', verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('artiste', 'Artiste'), ('admin', 'Admin')], default='admin', max_length=10, verbose_name='Rôle'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'like')), fields=('utilisateur', 'oeuvre'), name='unique_like_per_user_oeuvre'),
        ),
    ]
