# Generated by Django 5.2.7 on 2025-10-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0013_alter_interaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='Pixelette.interaction', verbose_name='Commentaire parent'),
        ),
    ]
