# Generated by Django 5.2.7 on 2025-10-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0014_interaction_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='filtered_content',
            field=models.TextField(blank=True, help_text='Version du contenu avec les mots inappropriés censurés', verbose_name='Contenu filtré'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='moderation_details',
            field=models.JSONField(blank=True, default=dict, help_text="Détails techniques de l'analyse IA (bad words, toxicité, etc.)", verbose_name='Détails de modération'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='moderation_reasons',
            field=models.TextField(blank=True, help_text='Raisons détaillées pour le signalement ou rejet', verbose_name='Raisons de modération'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='moderation_score',
            field=models.FloatField(default=0.0, help_text="Score calculé par l'IA pour évaluer le niveau de problème du contenu", verbose_name='Score de problème (0-1)'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('flagged', 'Signalé pour révision')], default='pending', max_length=20, verbose_name='Statut de modération'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de révision'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin qui a révisé manuellement cette interaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_interactions', to='Pixelette.utilisateur', verbose_name='Révisé par'),
        ),
    ]
