# Generated by Django 4.2 on 2025-10-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0013_merge_20251019_0042'),
        ('Pixelette', '0014_alter_interaction_options_interaction_parent_and_more'),
    ]

    operations = [
    ]
