# Generated by Django 4.2 on 2025-10-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0015_merge_20251022_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('artiste', 'Artiste'), ('admin', 'Admin')], default='user', max_length=10, verbose_name='Rôle'),
        ),
    ]
