# Generated by Django 4.2 on 2025-10-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0015_interaction_filtered_content_and_more'),
        ('Pixelette', '0016_alter_utilisateur_role'),
    ]

    operations = [
    ]
