# Generated by Django 5.2.7 on 2025-10-23 16:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixelette', '0017_merge_20251022_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAuthStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('user_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'temp_auth_storage',
            },
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('artiste', 'Artiste'), ('admin', 'Admin')], default='admin', max_length=10, verbose_name='Rôle'),
        ),
    ]
